version: "3.9"

services:
  storage:
    build: ./storage

  service1:
    build: ./service1

  management:
    build: ./management

  monitoring:
    build: ./monitoring

  gateway:
    build: ./gateway

